data = [{"companyCode": "510100010000", "name": "武侯区教育局", "value": [
    {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 1,
     "studyObjectNum": 1, "parentProjectName": "棕北项目1", "parentProjectProgress": 100.00, "parentProjectStatus": "已结束",
     "subject": "数学,语文,英语"},
    {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
     "studyObjectNum": 0, "parentProjectName": "研究物质生长的需求", "parentProjectProgress": 0, "parentProjectStatus": "已结束",
     "subject": "生物,化学"},
    {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
     "studyObjectNum": 0, "parentProjectName": "111", "parentProjectProgress": 0, "parentProjectStatus": "已结束",
     "subject": "数学,语文"},
    {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
     "studyObjectNum": 0, "parentProjectName": "英语视听说", "parentProjectProgress": 0, "parentProjectStatus": "已结束",
     "subject": "英语"},
    {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
     "studyObjectNum": 0, "parentProjectName": "杜甫", "parentProjectProgress": 0, "parentProjectStatus": "已结束",
     "subject": "数学,语文"}]}, {"companyCode": "510100010004", "name": "四川大学附属实验小学", "value": []},
        {"companyCode": "510100010005", "name": "成都市龙江路小学", "value": [
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "1", "parentProjectProgress": 0, "parentProjectStatus": "已结束",
             "subject": "数学"},
            {"parentProjectNum": 0, "subProjectNum": 5, "taskTotalNum": 5, "finishedTaskNum": 0, "teacherNum": 10,
             "studyObjectNum": 225, "parentProjectName": "龙小人工智能（AI）课程--3年级2020-2021学年第一学期活动",
             "parentProjectProgress": 0.00, "parentProjectStatus": "进行中", "subject": "人工智能,信息技术"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 2,
             "studyObjectNum": 228, "parentProjectName": "龙江路小学信息课程 项目活动集（三年级上期）", "parentProjectProgress": 0.00,
             "parentProjectStatus": "进行中", "subject": "人工智能,信息技术"}]},
        {"companyCode": "510100010006", "name": "成都市磨子桥小学", "value": []},
        {"companyCode": "510100010007", "name": "成都石室锦城外国语学校", "value": [
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "三顾云平台应用项目", "parentProjectProgress": 0,
             "parentProjectStatus": "进行中", "subject": "物理,数学,化学,语文,英语"},
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "123", "parentProjectProgress": 0, "parentProjectStatus": "进行中",
             "subject": "数学"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 17, "parentProjectName": "测试", "parentProjectProgress": 100.00,
             "parentProjectStatus": "进行中", "subject": "物理,生物,历史,数学,化学,语文,英语"}]},
        {"companyCode": "510100010008", "name": "四川大学附属实验小学西区", "value": []},
        {"companyCode": "510100010009", "name": "四川大学附属实验小学清水河分校", "value": []},
        {"companyCode": "510100010010", "name": "四川省成都市成都第十二中学（初中）", "value": [
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 2,
             "studyObjectNum": 83, "parentProjectName": "篮球比赛赛制研究", "parentProjectProgress": 0.00,
             "parentProjectStatus": "未开始", "subject": "体育,数学,语文"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 2,
             "studyObjectNum": 45, "parentProjectName": "123", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "体育,数学,语文"},
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "《水浒传》人物品读", "parentProjectProgress": 0,
             "parentProjectStatus": "已结束", "subject": "心理健康,信息技术,语文,思想品德,地理"},
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "学习三顾云", "parentProjectProgress": 0,
             "parentProjectStatus": "已结束", "subject": "数学"},
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "特色民居研究", "parentProjectProgress": 0,
             "parentProjectStatus": "已结束", "subject": "历史,语文,地理"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 3,
             "studyObjectNum": 92, "parentProjectName": "关于篮球赛制的研究性学习", "parentProjectProgress": 0.00,
             "parentProjectStatus": "未开始", "subject": "体育,数学,语文"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 2,
             "studyObjectNum": 1, "parentProjectName": "相互学习", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "数学"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 2,
             "studyObjectNum": 45, "parentProjectName": "中国地理地图应用", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "地理"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 2, "parentProjectName": "学校管理的信息化", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "数学,语文"},
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "现代地理教学", "parentProjectProgress": 0,
             "parentProjectStatus": "已结束", "subject": "地理"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 2,
             "studyObjectNum": 3, "parentProjectName": "管理现代化", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "物理,数学,语文"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 1, "parentProjectName": "地理教学中的自导式阅读", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "地理"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 45, "parentProjectName": "zz", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "物理"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 1, "parentProjectName": "跑步", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "生命·生态·安全"},
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "现代管理", "parentProjectProgress": 0, "parentProjectStatus": "已结束",
             "subject": "地理"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 45, "parentProjectName": "李白的美学", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "历史,语文"},
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "的撒个", "parentProjectProgress": 0, "parentProjectStatus": "已结束",
             "subject": "劳动"},
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "发生的提高", "parentProjectProgress": 0,
             "parentProjectStatus": "已结束", "subject": "数学"},
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "西点制作", "parentProjectProgress": 0, "parentProjectStatus": "已结束",
             "subject": "物理,英语"}]}, {"companyCode": "510100010011", "name": "成都市机投小学", "value": []},
        {"companyCode": "510100010012", "name": "棕北小学", "value": [
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 5, "finishedTaskNum": 1, "teacherNum": 6,
             "studyObjectNum": 5, "parentProjectName": "毕业研创课程", "parentProjectProgress": 0.00,
             "parentProjectStatus": "进行中", "subject": "道德与法制,体育,信息技术,数学,科学,语文,英语,美术,音乐,生命生态安全"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 2, "finishedTaskNum": 2, "teacherNum": 5,
             "studyObjectNum": 13, "parentProjectName": "《记一次游戏》习作教学", "parentProjectProgress": 0.00,
             "parentProjectStatus": "进行中", "subject": "语文"},
            {"parentProjectNum": 0, "subProjectNum": 4, "taskTotalNum": 4, "finishedTaskNum": 0, "teacherNum": 5,
             "studyObjectNum": 12, "parentProjectName": "一年级魔梯课程", "parentProjectProgress": 0.00,
             "parentProjectStatus": "进行中", "subject": "道德与法制,体育,信息技术,数学,科学,语文,英语,美术,音乐,生命生态安全"},
            {"parentProjectNum": 0, "subProjectNum": 2, "taskTotalNum": 2, "finishedTaskNum": 0, "teacherNum": 3,
             "studyObjectNum": 6, "parentProjectName": "三年级魔梯课程", "parentProjectProgress": 0.00,
             "parentProjectStatus": "进行中", "subject": "道德与法制,体育,信息技术,数学,科学,语文,英语,美术,音乐,生命生态安全"},
            {"parentProjectNum": 0, "subProjectNum": 4, "taskTotalNum": 4, "finishedTaskNum": 0, "teacherNum": 4,
             "studyObjectNum": 12, "parentProjectName": "五年级魔梯课程", "parentProjectProgress": 0.00,
             "parentProjectStatus": "进行中", "subject": "道德与法制,体育,信息技术,数学,科学,语文,英语,美术,音乐,生命生态安全"},
            {"parentProjectNum": 0, "subProjectNum": 5, "taskTotalNum": 5, "finishedTaskNum": 0, "teacherNum": 18,
             "studyObjectNum": 1175, "parentProjectName": "银杏街研学", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "信息技术,科学,语文,美术"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 5, "finishedTaskNum": 0, "teacherNum": 5,
             "studyObjectNum": 29, "parentProjectName": "棕北小学德育与少先队课程（教师版）", "parentProjectProgress": 0.00,
             "parentProjectStatus": "进行中", "subject": "道德与法制,信息技术,美术,音乐"},
            {"parentProjectNum": 0, "subProjectNum": 2, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 12,
             "studyObjectNum": 189, "parentProjectName": "五年级魔梯课程------环境复刻", "parentProjectProgress": 0.00,
             "parentProjectStatus": "进行中", "subject": "信息技术,科学,语文,美术"},
            {"parentProjectNum": 0, "subProjectNum": 4, "taskTotalNum": 4, "finishedTaskNum": 0, "teacherNum": 24,
             "studyObjectNum": 892, "parentProjectName": "一年级魔梯课程（学生版）", "parentProjectProgress": 25.00,
             "parentProjectStatus": "进行中", "subject": "信息技术,科学,语文,美术"},
            {"parentProjectNum": 0, "subProjectNum": 3, "taskTotalNum": 3, "finishedTaskNum": 0, "teacherNum": 17,
             "studyObjectNum": 831, "parentProjectName": "三年级魔梯课程（学生版）", "parentProjectProgress": 0.00,
             "parentProjectStatus": "进行中", "subject": "信息技术,科学,语文,美术,生命生态安全"},
            {"parentProjectNum": 0, "subProjectNum": 2, "taskTotalNum": 2, "finishedTaskNum": 0, "teacherNum": 3,
             "studyObjectNum": 96, "parentProjectName": "五年级魔梯课程------模拟停车场", "parentProjectProgress": 0.00,
             "parentProjectStatus": "进行中", "subject": "信息技术,数学,科学,语文,美术"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 2, "finishedTaskNum": 0, "teacherNum": 6,
             "studyObjectNum": 160, "parentProjectName": "2021第四届毕业研创课程", "parentProjectProgress": 0.00,
             "parentProjectStatus": "进行中", "subject": "道德与法制,体育,信息技术,数学,科学,语文,英语,美术,音乐"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 35,
             "studyObjectNum": 1152, "parentProjectName": "2020-2021学年度上期寒假健康娃娃红领巾雏鹰争章活动",
             "parentProjectProgress": 0.00, "parentProjectStatus": "进行中", "subject": "道德与法制,信息技术,语文,美术,音乐"}]},
        {"companyCode": "510100010025", "name": "成都市第四十三中学校", "value": []},
        {"companyCode": "510100010026", "name": "成都市簇桥小学校", "value": []},
        {"companyCode": "510100010027", "name": "成都市弟维小学", "value": []},
        {"companyCode": "510100010028", "name": "成都市华西小学", "value": []},
        {"companyCode": "510100010029", "name": "成都市金花中学", "value": [
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 3,
             "studyObjectNum": 215, "parentProjectName": "化学千变万化，实验循规探秘", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "化学"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 3, "parentProjectName": "英语海报学习", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "英语"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 3, "parentProjectName": "英语海报学习", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "英语"}]},
        {"companyCode": "510100010030", "name": "成都市武侯实验小学", "value": []},
        {"companyCode": "510100010031", "name": "棕北中学西区实验学校（中学）", "value": [
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "成都市棕北中学西区实验学校劳动课程", "parentProjectProgress": 0,
             "parentProjectStatus": "进行中", "subject": "心理健康,道德与法制,生物,生命·生态·安全,思想品德,劳动"}]},
        {"companyCode": "510100010032", "name": "成都市华兴小学", "value": []},
        {"companyCode": "510100010033", "name": "成都市龙祥路小学", "value": [
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "英语学科核心素养培养", "parentProjectProgress": 0,
             "parentProjectStatus": "已结束", "subject": "英语"},
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "巴塘连北京", "parentProjectProgress": 0,
             "parentProjectStatus": "已结束", "subject": "音乐"},
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "《花鸟画---猫头鹰》", "parentProjectProgress": 0,
             "parentProjectStatus": "已结束", "subject": "美术"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 243, "parentProjectName": "《迎来春色换人间》", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "音乐"},
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "中段语文赛研活动", "parentProjectProgress": 0,
             "parentProjectStatus": "已结束", "subject": "语文"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 26,
             "studyObjectNum": 4, "parentProjectName": "新时代劳动美", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "道德与法制,语文"},
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "英语学科教研活动", "parentProjectProgress": 0,
             "parentProjectStatus": "已结束", "subject": "英语"},
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "英语学科教研", "parentProjectProgress": 0,
             "parentProjectStatus": "已结束", "subject": "英语"},
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "整本书阅读", "parentProjectProgress": 0,
             "parentProjectStatus": "进行中", "subject": "语文"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 2, "parentProjectName": "数学教研", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "数学"},
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "模仿走与游戏", "parentProjectProgress": 0,
             "parentProjectStatus": "已结束", "subject": "体育"},
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "教室", "parentProjectProgress": 0, "parentProjectStatus": "已结束",
             "subject": "数学"},
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "模仿走与游戏", "parentProjectProgress": 0,
             "parentProjectStatus": "已结束", "subject": "体育"},
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "合作跳绳", "parentProjectProgress": 0, "parentProjectStatus": "已结束",
             "subject": "体育"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 49, "parentProjectName": "声音的产生", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "科学"},
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "直拍颠球", "parentProjectProgress": 0, "parentProjectStatus": "已结束",
             "subject": "体育"},
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "跑步走与立定", "parentProjectProgress": 0,
             "parentProjectStatus": "已结束", "subject": "体育"},
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "11月25日周三班会活动，开设“家长课堂”", "parentProjectProgress": 0,
             "parentProjectStatus": "已结束", "subject": "语文"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 3, "parentProjectName": "学生阅读活动", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "语文"},
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "中段阅读理解课堂渗透及深入", "parentProjectProgress": 0,
             "parentProjectStatus": "已结束", "subject": "语文"},
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "高段数学赛研活动", "parentProjectProgress": 0,
             "parentProjectStatus": "已结束", "subject": "数学"},
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "模仿走与游戏", "parentProjectProgress": 0,
             "parentProjectStatus": "已结束", "subject": "体育"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 44, "parentProjectName": "跳短绳", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "体育"},
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "粘土 三星堆", "parentProjectProgress": 0,
             "parentProjectStatus": "已结束", "subject": "美术"}]},
        {"companyCode": "510100010036", "name": "成都市桐梓林小学", "value": []},
        {"companyCode": "510100010037", "name": "成都市武侯区磨子桥小学分校", "value": []},
        {"companyCode": "510100010038", "name": "四川省成都市成都第十二中学（高中）", "value": []},
        {"companyCode": "510100010039", "name": "成都市科华中路小学", "value": [
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "信息技术教学", "parentProjectProgress": 0,
             "parentProjectStatus": "已结束", "subject": "信息技术"}]},
        {"companyCode": "510100010040", "name": "成都市行知实验小学", "value": []},
        {"companyCode": "510100010041", "name": "北京第二外国语学院成都附属小学", "value": [
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "测试测", "parentProjectProgress": 0, "parentProjectStatus": "已结束",
             "subject": "体育1"},
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "学科信息技术研讨学习", "parentProjectProgress": 0,
             "parentProjectStatus": "进行中", "subject": "信息技术,数学,体育2,科学,语文,思维,体育1,英语,美术,音乐"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 45, "parentProjectName": "名师工作室", "parentProjectProgress": 100.00,
             "parentProjectStatus": "进行中", "subject": "信息技术,数学,体育2,体育1,体育3,音乐"}]},
        {"companyCode": "510100010042", "name": "四川省成都市西北中学外国语学校", "value": [
            {"parentProjectNum": 0, "subProjectNum": 2, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 6,
             "studyObjectNum": 798, "parentProjectName": "西外艺术测评", "parentProjectProgress": 0.00,
             "parentProjectStatus": "进行中", "subject": "信息技术,美术,音乐"}]},
        {"companyCode": "510100010043", "name": "成都市武侯实验中学", "value": [
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "《王者荣耀》背后的人文研究", "parentProjectProgress": 0,
             "parentProjectStatus": "进行中", "subject": "政治,物理,通用技术,科学,语文"},
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "中小学微创业", "parentProjectProgress": 0,
             "parentProjectStatus": "进行中", "subject": "道德与法制,生命·生态·安全,数学,思想品德,生命生态安全"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 89, "parentProjectName": "为语文课文配插画", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "语文,美术"}]},
        {"companyCode": "510100010044", "name": "成都市龙江路小学中粮祥云分校", "value": []},
        {"companyCode": "510100010045", "name": "棕北中学西区实验学校（小学）", "value": []},
        {"companyCode": "510100010046", "name": "成都市红牌楼小学校", "value": [
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 5,
             "studyObjectNum": 165, "parentProjectName": "人工智能教学", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "信息技术,数学,语文"}]},
        {"companyCode": "510100010048", "name": "成都市龙江路小学分校", "value": [
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 182, "parentProjectName": "我设计的船", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "科学"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 45, "parentProjectName": "多姿多彩的靠垫", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "数学,美术"}]},
        {"companyCode": "510100010049", "name": "成都市龙江路小学武侯新城分校", "value": [
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "“校园一方土 荒漠千点绿”耕园主题展投标项目式学习课程", "parentProjectProgress": 0,
             "parentProjectStatus": "已结束", "subject": "信息技术,科学,语文,美术,生安（综合实践）"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 1, "parentProjectName": "1", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "数学,语文"},
            {"parentProjectNum": 0, "subProjectNum": 6, "taskTotalNum": 6, "finishedTaskNum": 0, "teacherNum": 11,
             "studyObjectNum": 168, "parentProjectName": "校园一方土 荒漠千点绿——学校“耕园”项目式学习", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "信息技术,数学,科学,语文,美术,生安（综合实践）"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 4, "finishedTaskNum": 0, "teacherNum": 5,
             "studyObjectNum": 18, "parentProjectName": "“光盘行动  我们的行动”PBL项目式学习", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "数学,科学,语文,生安（综合实践）,道德与法治,劳动"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 5,
             "studyObjectNum": 49, "parentProjectName": "“活水园”污水净化系统改进PBL活动", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "信息技术,科学,数学,语文,道德与法治"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 8, "finishedTaskNum": 0, "teacherNum": 6,
             "studyObjectNum": 9, "parentProjectName": "PBL融合课程——垃圾分类课程", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "数学,科学,语文,美术,生安（综合实践）,道德与法治"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 3, "finishedTaskNum": 0, "teacherNum": 6,
             "studyObjectNum": 39, "parentProjectName": "“春分·春天”学科联动 PBL活动", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "数学,语文,美术,生安（综合实践）"}]},
        {"companyCode": "510100010050", "name": "成都市太平小学校", "value": [
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "语文", "parentProjectProgress": 0, "parentProjectStatus": "已结束",
             "subject": "数学,语文,英语"},
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "语文", "parentProjectProgress": 0, "parentProjectStatus": "已结束",
             "subject": "数学,语文,英语"}]}, {"companyCode": "510100010051", "name": "成都市武侯实验中学附属小学", "value": [
        {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 1,
         "studyObjectNum": 46, "parentProjectName": "计算与应用能力", "parentProjectProgress": 0.00,
         "parentProjectStatus": "进行中", "subject": "数学"},
        {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 1,
         "studyObjectNum": 1, "parentProjectName": "XXX", "parentProjectProgress": 100.00, "parentProjectStatus": "已结束",
         "subject": "信息技术,生命与安全3"}]}, {"companyCode": "510100010052", "name": "成都市棕北中学（科院校区）", "value": [
        {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
         "studyObjectNum": 0, "parentProjectName": "棕北中学", "parentProjectProgress": 0, "parentProjectStatus": "已结束",
         "subject": "化学"},
        {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 1,
         "studyObjectNum": 3, "parentProjectName": "三顾云二期平台学习", "parentProjectProgress": 100.00,
         "parentProjectStatus": "已结束", "subject": "体育,数学,语文,英语,地理,音乐"}]},
        {"companyCode": "510100010053", "name": "成都市武侯计算机实验小学", "value": [
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 5,
             "studyObjectNum": 43, "parentProjectName": "根据食物的酸碱性设计学校一周午餐食谱", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "信息技术,数学,科学,语文,美术"}]},
        {"companyCode": "510100010054", "name": "成都市马家河小学", "value": [
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "实验", "parentProjectProgress": 0, "parentProjectStatus": "已结束",
             "subject": "信息技术"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 1, "teacherNum": 2,
             "studyObjectNum": 5, "parentProjectName": "2020年度校级课题——小学英语”Handwriting”规范实践研究",
             "parentProjectProgress": 0.00, "parentProjectStatus": "进行中", "subject": "英语"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 5, "parentProjectName": "2020校级课题——基于体育核心素养下提高小学生体质健康水平的实践研究",
             "parentProjectProgress": 0.00, "parentProjectStatus": "进行中", "subject": "体育,语文"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 5, "parentProjectName": "2020年校级课题——“纸飞飞”作业形式对作业完成度的促进作用研究",
             "parentProjectProgress": 0.00, "parentProjectStatus": "进行中", "subject": "语文"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 4, "parentProjectName": "2020年校级课题——城郊小学问题心理学生个体辅导方法探究", "parentProjectProgress": 0.00,
             "parentProjectStatus": "进行中", "subject": "数学,语文"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 1, "teacherNum": 1,
             "studyObjectNum": 5, "parentProjectName": "2020年校级课题——如何将三国蜀汉文融入剪纸主题教学的实践研究",
             "parentProjectProgress": 0.00, "parentProjectStatus": "进行中", "subject": "信息技术,美术"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 5, "parentProjectName": "2020年校级课题——小学劳动教育模式的探究---以农场劳动种植为例",
             "parentProjectProgress": 0.00, "parentProjectStatus": "进行中", "subject": "体育,生命·生态·安全,语文,英语"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 4, "parentProjectName": "2020年校级课题——小数二年级上册数学作业探究", "parentProjectProgress": 0.00,
             "parentProjectStatus": "进行中", "subject": "心理健康,数学"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 5, "parentProjectName": "2020年校级课题——在课内阅读中提升小学低段学生提问能力的实践研究",
             "parentProjectProgress": 0.00, "parentProjectStatus": "进行中", "subject": "语文"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 5, "parentProjectName": "2020年校级课题——基于思维导图的小学数学复习教学研究", "parentProjectProgress": 0.00,
             "parentProjectStatus": "进行中", "subject": "数学,劳动"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 4, "parentProjectName": "2020年校级课题——基于二十四节气的小学劳动教育实践研究", "parentProjectProgress": 0.00,
             "parentProjectStatus": "进行中", "subject": "生命·生态·安全,数学,语文"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 4, "parentProjectName": "2020年校级课题——小学生劳动教育及良好行为习惯养成的策略研究",
             "parentProjectProgress": 0.00, "parentProjectStatus": "进行中", "subject": "语文"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 3, "parentProjectName": "2020年校级课题——情景教学", "parentProjectProgress": 0.00,
             "parentProjectStatus": "进行中", "subject": "数学,语文"},
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "我的大自然神奇之旅——发现植物篇", "parentProjectProgress": 0,
             "parentProjectStatus": "已结束", "subject": "科学,语文,美术,劳动"},
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "我的大自然神奇之旅——发现动物篇", "parentProjectProgress": 0,
             "parentProjectStatus": "已结束", "subject": "科学,语文,美术"}]},
        {"companyCode": "510100010056", "name": "四川省成都市武侯高级中学", "value": []},
        {"companyCode": "510100010057", "name": "成都市武顺街小学", "value": [
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 50, "parentProjectName": "运算律和运算性质整理", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "数学"},
            {"parentProjectNum": 0, "subProjectNum": 4, "taskTotalNum": 4, "finishedTaskNum": 0, "teacherNum": 4,
             "studyObjectNum": 39, "parentProjectName": "《学本课堂》", "parentProjectProgress": 0.00,
             "parentProjectStatus": "进行中", "subject": "数学,语文"},
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "“学本课堂”随笔", "parentProjectProgress": 0,
             "parentProjectStatus": "已结束", "subject": "语文"},
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "学本课堂随笔", "parentProjectProgress": 0,
             "parentProjectStatus": "已结束", "subject": "语文"},
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "学本课堂", "parentProjectProgress": 0, "parentProjectStatus": "已结束",
             "subject": "语文"},
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "学本课堂", "parentProjectProgress": 0, "parentProjectStatus": "已结束",
             "subject": "语文"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 101, "parentProjectName": "百分数的认识教案（11.10已上）", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "数学"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 101, "parentProjectName": "《百分数的认识》板书（11.10已上）", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "数学"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 6, "parentProjectName": "《认识三角形和四边形》单元研讨", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "数学"},
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "《5的乘法口诀》教案", "parentProjectProgress": 0,
             "parentProjectStatus": "已结束", "subject": "数学"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 1, "parentProjectName": "学本学习反思", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "数学"},
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "《比尾巴》教案", "parentProjectProgress": 0,
             "parentProjectStatus": "已结束", "subject": "语文"},
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "《小书包》教案", "parentProjectProgress": 0,
             "parentProjectStatus": "已结束", "subject": "语文"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 6, "parentProjectName": "分物游戏-教学设计", "parentProjectProgress": 0.00,
             "parentProjectStatus": "进行中", "subject": "数学"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 19, "parentProjectName": "成都市武顺街小学民主评议", "parentProjectProgress": 0.00,
             "parentProjectStatus": "进行中", "subject": "足球,语文,英语,美术,音乐,道德与法制,体育,生命·生态·安全,信息技术,数学,科学,篮球,网球"}]},
        {"companyCode": "510100010058", "name": "成都市金兴北路小学", "value": []},
        {"companyCode": "510100010059", "name": "成都市锦里小学", "value": [
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 5,
             "studyObjectNum": 2, "parentProjectName": "四练五好", "parentProjectProgress": 0.00,
             "parentProjectStatus": "进行中", "subject": "体育与健康,数学,语文,音乐"}]},
        {"companyCode": "510100010060", "name": "成都市武侯科技园小学", "value": [
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "教学节", "parentProjectProgress": 0, "parentProjectStatus": "进行中",
             "subject": "信息技术"},
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "2", "parentProjectProgress": 0, "parentProjectStatus": "已结束",
             "subject": "语文"}]}, {"companyCode": "510100010061", "name": "四川大学附属实验小学江安河分校", "value": []},
        {"companyCode": "510100010063", "name": "四川音乐学院附属实验小学", "value": []},
        {"companyCode": "510100010064", "name": "成都市晋阳小学", "value": [
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "如何制作单元知结构图", "parentProjectProgress": 0,
             "parentProjectStatus": "已结束", "subject": "数学,美术"}]},
        {"companyCode": "510100010065", "name": "成都市太平寺西区小学", "value": []},
        {"companyCode": "510100010066", "name": "四川大学附属中学西区学校", "value": []},
        {"companyCode": "510100010067", "name": "成都市玉林小学", "value": [
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 43, "parentProjectName": "京剧趣谈", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "语文"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 43, "parentProjectName": "小报展示", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "语文"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 43, "parentProjectName": "经典展示", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "语文"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 43, "parentProjectName": "诵经典  写经典（钢笔字书写展示、经典诵读视频）", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "语文"},
            {"parentProjectNum": 0, "subProjectNum": 2, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 2,
             "studyObjectNum": 86, "parentProjectName": "故宫参观路线图；故宫一两个景点讲解词", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "语文"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 48, "parentProjectName": "家务活动", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "语文"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 42, "parentProjectName": "笔尖流出的故事", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "语文"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 43, "parentProjectName": "寻找武侯最美风景  摄影作品", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "道德与法制"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 47, "parentProjectName": "诗乐园", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "语文"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 44, "parentProjectName": "语文作业", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "语文"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 43, "parentProjectName": "与古诗词交朋友", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "语文"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 43, "parentProjectName": "与古诗词交朋友", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "语文"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 42, "parentProjectName": "与古诗词交朋友", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "语文"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 42, "parentProjectName": "与古诗词交朋友", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "语文"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 42, "parentProjectName": "与古诗词交朋友", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "语文"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 42, "parentProjectName": "与古诗词交朋友", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "语文"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 42, "parentProjectName": "与古诗词交朋友", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "语文"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 177, "parentProjectName": "用纸造一座“桥”", "parentProjectProgress": 0.00,
             "parentProjectStatus": "进行中", "subject": "科学"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 43, "parentProjectName": "制作我的小乐器", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "科学"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 45, "parentProjectName": "《古诗二首》诵读比赛", "parentProjectProgress": 0.00,
             "parentProjectStatus": "进行中", "subject": "语文"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 43, "parentProjectName": "竹节人展示", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "语文"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 47, "parentProjectName": "背诵《司马光》", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "语文"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 46, "parentProjectName": "古诗结合手工学习", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "语文,美术"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 46, "parentProjectName": "《司马光》朗诵", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "语文"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 43, "parentProjectName": "朗诵、背诵《月光曲》9自然段", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "语文"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 175, "parentProjectName": "“乘风破浪”船形机器人", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "科学"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 189, "parentProjectName": "“乘风破浪”船型机器人", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "科学"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 134, "parentProjectName": "制作我的小乐器", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "科学"}]},
        {"companyCode": "510100010068", "name": "四川省成都市西北中学", "value": []},
        {"companyCode": "510100010075", "name": "成都市沙堰小学", "value": [
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "劳动教育", "parentProjectProgress": 0, "parentProjectStatus": "已结束",
             "subject": "语文"}]}, {"companyCode": "510100010087", "name": "四川大学附属中学新城分校", "value": [
        {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 18,
         "studyObjectNum": 47, "parentProjectName": "新城", "parentProjectProgress": 100.00, "parentProjectStatus": "已结束",
         "subject": "语文"},
        {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 2,
         "studyObjectNum": 7, "parentProjectName": "arduino创客", "parentProjectProgress": 100.00,
         "parentProjectStatus": "已结束", "subject": "信息技术"}]}, {"companyCode": "510100010088", "name": "北京第二外国语学院成都附属中学",
                                                              "value": [{"parentProjectNum": 0, "subProjectNum": 0,
                                                                         "taskTotalNum": 0, "finishedTaskNum": 0,
                                                                         "teacherNum": 0, "studyObjectNum": 0,
                                                                         "parentProjectName": "所需的信息",
                                                                         "parentProjectProgress": 0,
                                                                         "parentProjectStatus": "已结束",
                                                                         "subject": "人工智能,通用技术,信息技术"}]},
        {"companyCode": "510100010094", "name": "成都石室双楠实验学校（小学部）", "value": []},
        {"companyCode": "510100010095", "name": "成都石室双楠实验学校（初中部）", "value": []},
        {"companyCode": "202009002", "name": "武侯区运营团队", "value": [
            {"parentProjectNum": 0, "subProjectNum": 2, "taskTotalNum": 2, "finishedTaskNum": 0, "teacherNum": 6,
             "studyObjectNum": 60, "parentProjectName": "校-项目", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "体育,数学,语文,英语"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 3,
             "studyObjectNum": 30, "parentProjectName": "校项目------项目名称最多三十五个字项目名称最多三十五个字项目名称",
             "parentProjectProgress": 100.00, "parentProjectStatus": "已结束", "subject": "政治,生物,数学,化学,语文,英语"},
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "123", "parentProjectProgress": 0, "parentProjectStatus": "已结束",
             "subject": "自然"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 4,
             "studyObjectNum": 34, "parentProjectName": "校-验证项目进度", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "数学,语文"},
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "豆芽种植", "parentProjectProgress": 0, "parentProjectStatus": "已结束",
             "subject": "数学,语文,英语,自然"},
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "花木成畦手自栽asd", "parentProjectProgress": 0,
             "parentProjectStatus": "已结束", "subject": "物理,生物,数学,化学,语文,英语"},
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "尔特瑞特", "parentProjectProgress": 0, "parentProjectStatus": "已结束",
             "subject": "语文"},
            {"parentProjectNum": 0, "subProjectNum": 2, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 2,
             "studyObjectNum": 2, "parentProjectName": "花木成畦手自栽要", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "语文"},
            {"parentProjectNum": 0, "subProjectNum": 2, "taskTotalNum": 1, "finishedTaskNum": 1, "teacherNum": 2,
             "studyObjectNum": 3, "parentProjectName": "武侯项目学习", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "数学,语文"},
            {"parentProjectNum": 0, "subProjectNum": 2, "taskTotalNum": 3, "finishedTaskNum": 1, "teacherNum": 4,
             "studyObjectNum": 4, "parentProjectName": "三国风云", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "历史,语文,地理"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 4,
             "studyObjectNum": 30, "parentProjectName": "校---测试项目", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "数学,语文"},
            {"parentProjectNum": 0, "subProjectNum": 2, "taskTotalNum": 2, "finishedTaskNum": 1, "teacherNum": 4,
             "studyObjectNum": 4, "parentProjectName": "三国", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "数学,语文,英语,地理"},
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "1", "parentProjectProgress": 0, "parentProjectStatus": "已结束",
             "subject": "语文"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 1,
             "studyObjectNum": 3, "parentProjectName": "[%--`~!@#$^&*()=|{}':;',\\\\[\\\\].<>/?",
             "parentProjectProgress": 100.00, "parentProjectStatus": "已结束", "subject": "语文"},
            {"parentProjectNum": 0, "subProjectNum": 0, "taskTotalNum": 0, "finishedTaskNum": 0, "teacherNum": 0,
             "studyObjectNum": 0, "parentProjectName": "11", "parentProjectProgress": 0, "parentProjectStatus": "已结束",
             "subject": "数学,语文"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 4,
             "studyObjectNum": 34, "parentProjectName": "校单变多子项目", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "数学,语文,英语"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 3,
             "studyObjectNum": 2, "parentProjectName": "s", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "数学,语文,英语"},
            {"parentProjectNum": 0, "subProjectNum": 2, "taskTotalNum": 3, "finishedTaskNum": 3, "teacherNum": 3,
             "studyObjectNum": 2, "parentProjectName": "三国风云研究", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "数学,语文"},
            {"parentProjectNum": 0, "subProjectNum": 2, "taskTotalNum": 3, "finishedTaskNum": 3, "teacherNum": 4,
             "studyObjectNum": 2, "parentProjectName": "对豌豆的研究", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "数学,语文"},
            {"parentProjectNum": 0, "subProjectNum": 1, "taskTotalNum": 1, "finishedTaskNum": 0, "teacherNum": 5,
             "studyObjectNum": 30, "parentProjectName": "每日学习", "parentProjectProgress": 100.00,
             "parentProjectStatus": "已结束", "subject": "数学,语文"}]},
        {"companyCode": "202009004", "name": "武侯区西蜀实验学校", "value": []},
        {"companyCode": "202009024", "name": "成都市武侯外国语学校", "value": []},
        {"companyCode": "510100010047", "name": "成都市龙江路小学（南区）", "value": []},
        {"companyCode": "510100010055", "name": "成都市群星美术学校", "value": []},
        {"companyCode": "510100010079", "name": "成都市通江实验学校", "value": []},
        {"companyCode": "510100010076", "name": "成都市武侯区育仁实验学校", "value": []},
        {"companyCode": "510100010077", "name": "成都市凉井实验学校", "value": []},
        {"companyCode": "510100010078", "name": "成都市锦官新城小学", "value": []},
        {"companyCode": "510100010080", "name": "成都武侯外国语学校", "value": []},
        {"companyCode": "510100010081", "name": "成都市武侯区西蜀实验学校", "value": []},
        {"companyCode": "510100010082", "name": "成都市第57实验学校", "value": []},
        {"companyCode": "510100010083", "name": "成都西川中学", "value": []},
        {"companyCode": "510100010084", "name": "成都市武侯区启明学校", "value": []},
        {"companyCode": "510100010085", "name": "成都市春晖学校", "value": []},
        {"companyCode": "510100010086", "name": "成都石室佳兴外国语学校", "value": []},
        {"companyCode": "510100010091", "name": "武侯区光明实验学校", "value": []},
        {"companyCode": "510100010089", "name": "成都丹勋实验学校", "value": []},
        {"companyCode": "510100010090", "name": "成都市金花实验学校", "value": []},
        {"companyCode": "510100010092", "name": "成都市武侯区星光学校", "value": []},
        {"companyCode": "510100010093", "name": "成都七中实验学校", "value": []},
        {"companyCode": "510100010109", "name": "成都市武侯区西川实验学校", "value": []},
        {"companyCode": "510100010112", "name": "成都市金花光明学校", "value": []},
        {"companyCode": "510100010114", "name": "成都市启明实验学校", "value": []},
        {"companyCode": "510100010116", "name": "成都领川外国语学校", "value": []},
        {"companyCode": "510100010062", "name": "四川省成都市礼仪职业中学", "value": []},
        {"companyCode": "202011001", "name": "成都市乡镇学校", "value": []},
        {"companyCode": "510100010113", "name": "成都市武侯区特殊教育学校", "value": []},
        {"companyCode": "202011002", "name": "四川大学附属实验小学南区", "value": []},
        {"companyCode": "202012003", "name": "成都市棕北中学（桐梓林校区）", "value": []}]

companyCodeList = []
companyNameList = []

for d in data:
    companyCode = d['companyCode']
    companyName = d['name']
    companyCodeList.append(companyCode)
    companyNameList.append(companyName)

print(companyCodeList)
print(companyNameList)